version: "3.9"

services:

  jaeger: 
    image: jaegertracing/all-in-one:latest  
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686
    networks:
      - ovb-demos-ecommerce

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ${PWD}/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   
      - "4318:4318" 
    command: ["--config=/etc/otel-collector-config.yaml"]
    depends_on:
      - jaeger
    links:
      - jaeger
    networks:
      - ovb-demos-ecommerce

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    restart: always
    networks: 
      - ovb-demos-ecommerce

  microsservice-account:
    build: 
      context: .
      dockerfile: ${PWD}/Dockerfile
    container_name: 'microsservice-account'
    volumes: 
      - ${PWD}/Volumes/appsettings.json:/app/appsettings.json
      - ${PWD}/Volumes/appsettings-worker.json:/app-worker/appsettings.json
      - ${PWD}/Volumes/microsservice-account-command-db.sql:/docker-entrypoint-initdb.d/microsservice-account-command-db.sql
    networks:
      - ovb-demos-ecommerce   

  pgadmin:
    image: dpage/pgadmin4
    user: root
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "otavio@otavio.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "8080:80"
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - ovb-demos-ecommerce

  postgresquery:
    image: postgres
    container_name: postgresquery
    volumes:
      - ${PWD}/Volumes/microsservice-account-worker-cqrs.sql:/docker-entrypoint-initdb.d/microsservice-account-worker-cqrs.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    restart: always
    networks: 
      - ovb-demos-ecommerce-query-consult
  
  pgadminquery:
    image: dpage/pgadmin4
    user: root
    container_name: pgadminquery
    environment:
      PGADMIN_DEFAULT_EMAIL: "otavio@otavio.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "8081:80"
    restart: always
    links:
      - postgresquery
    depends_on:
      - postgresquery
    networks:
      - ovb-demos-ecommerce-query-consult

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    networks:
      - ovb-demos-ecommerce

networks:
  ovb-demos-ecommerce:
    driver: bridge  
  ovb-demos-ecommerce-query-consult:
    driver: bridge