version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    restart: always
    networks: 
      - ovb-demos-ecommerce

  pgadmin:
    image: dpage/pgadmin4
    user: root
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "otavio@otavio.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "8080:80"
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - ovb-demos-ecommerce

  microsservice-account:
    build: 
      dockerfile: ./src/Account/OVB.Demos.Ecommerce.Microsservices.AccountManagement.WebGrpc/.
    container_name: 'microsservice-account'
    volumes: 
      - ${PWD}/Volumes/microsservice-account-appsettings.json:/app/appsettings.json
    ports:
      - "5001:80"
    networks:
      - ovb-demos-ecommerce   

networks:
  ovb-demos-ecommerce:
    driver: bridge  