version: "3.9"

services:
  jaeger: 
    image: jaegertracing/all-in-one:latest  
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686
    networks:
      - ovb-demos-ecommerce-opentelemetry

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ${PWD}/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   
      - "4318:4318" 
    command: ["--config=/etc/otel-collector-config.yaml"]
    depends_on:
      - jaeger
    links:
      - jaeger
    networks:
      - ovb-demos-ecommerce-opentelemetry

networks:
  ovb-demos-ecommerce-opentelemetry:
    driver: bridge  